name: cogisoft-pb

services:
  pb:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PB_EMAIL=${PB_EMAIL:-cogitoteamdev@gmail.com}
      - PB_PASSWORD=${PB_PASSWORD}
    volumes:
      - ./pb_data:/pb/pb_data
